language: ruby
script: bundle exec rspec
bundler_args: --without development
before_install:
  - 'sudo apt-get install zookeeper zookeeperd'
  - 'sudo service zookeeper restart && sleep 3 || true'
rvm:
  - jruby-19mode
  - jruby-head
jdk:
  - openjdk7